version: '3.1'
services:
  mongo:
    image: mongo
    container_name: ouioui_states_db
    command: mongod --port 8003
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: state
    ports:
      - 8003:8003
    volumes:
          - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  
  server:
    build: .
    image: gabimgarciarom/ouioui_states_ms:ouioui_states_ms
    container_name: ouioui_states_ms
    restart: always
    ports:
      - 5000:80
    environment:
      MongoDB__Host: mongo
    depends_on:
      - mongo