version: '3.1'
services:
  mongo:
    image: mongo
    container_name: states-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: state
    ports:
      - 27017:27017
    volumes:
          - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  
  server:
    build: .
    container_name: states-ms
    restart: always
    ports:
      - 5000:80
    environment:
      MongoDB__Host: mongo
    depends_on:
      - mongo